spring:
  application:
    name: findu

  datasource:
    url: jdbc:postgresql://localhost:5432/findu_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 구글 로그인 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "ClientId"

            client-secret: "ClientSecret"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account

# JWT 설정
jwt:
  secret: "findu_secret_key_findu_secret_key_findu_secret_key_12345"
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

server:
  port: 8080